"""add email to event version

Revision ID: 81bc1c45c58d
Revises: 3aac63303b73
Create Date: 2025-05-25 17:34:00.583288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '81bc1c45c58d'
down_revision: Union[str, None] = '3aac63303b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventversion', sa.Column('editor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventversion', 'editor_email')
    # ### end Alembic commands ###
